### ISSUE TITLE
Not working on server for 1.12.1

### ISSUE THREAD

**Issue by Zygus42** [JaSpr/FasterLadderClimbing#4]
FasterLadderClimbing-1.12-0.1-127

Tested this in solo survival and was fine, but did not work once we put it on our server - always possible some other mod is interfering with it of course.

**Comment by JaSpr** [comment]
The mod is designed to disable if Quark is present, since quark already speeds up the descent.  Can you confirm the pack does not have Quark?

**Comment by JaSpr** [comment]
I've removed quark from the list of conflicting mods so that it will still work in modpacks that have quark installed.

bc54b74e09aeec759669a0db0758db28f01419f4

**Comment by JaSpr** [comment]
https://minecraft.curseforge.com/projects/faster-ladder-climbing/files/2512758
