### ISSUE TITLE
[1.12.2] Climbing speed no longer increased

### ISSUE THREAD

**Issue by Shahelion** [JaSpr/FasterLadderClimbing#5]
No idea why. Going down is still faster.

Mod list: https://hastebin.com/fibahanuvu.css

**Comment by JaSpr** [comment]
The mod is designed to disable if Quark is installed, since they conflict.  Quark will also try to speed you up as you go down ladders...  I'm gonna take a look at some stuff and leave this ticket open for the time being.

**Comment by JaSpr** [comment]
I've removed quark from the conflict list, so it will run even if quark is included in the pack.  This means you could end up going down ladders EVEN FASTER.

Pending approval on curseforge.

bc54b74e09aeec759669a0db0758db28f01419f4

**Comment by Shahelion** [comment]
I mean light-speed down ladders sounds fun.

Is it possible to only disable the speed boost in one direction?

**Comment by JaSpr** [comment]
Not easily.  It could be done, but it would require a fairly extensive refactor

**Comment by JaSpr** [comment]
https://minecraft.curseforge.com/projects/faster-ladder-climbing/files/2512758
